# Generated by Django 5.2.5 on 2025-08-17 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=255)),
                ('is_deployed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Node Families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('default_value', models.TextField(blank=True)),
                ('datatype', models.CharField(blank=True, choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('file', 'File')], max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeFamilyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='flow_builder_app.nodefamily')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='flow_builder_app.nodefamily')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.AddField(
            model_name='nodefamily',
            name='child_nodes',
            field=models.ManyToManyField(related_name='parent_nodes', through='flow_builder_app.NodeFamilyRelationship', to='flow_builder_app.nodefamily'),
        ),
        migrations.CreateModel(
            name='NodeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('script', models.FileField(blank=True, null=True, upload_to='node_scripts/%Y/%m/%d/')),
                ('changelog', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='flow_builder_app.nodefamily')),
            ],
            options={
                'ordering': ['family', '-version'],
            },
        ),
        migrations.CreateModel(
            name='NodeExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('triggered_by', models.CharField(max_length=255)),
                ('artifacts', models.JSONField(default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='flow_builder_app.nodeversion')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeVersionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('child_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='flow_builder_app.nodeversion')),
                ('parent_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='flow_builder_app.nodeversion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='nodeversion',
            name='linked_subversions',
            field=models.ManyToManyField(related_name='parent_versions', through='flow_builder_app.NodeVersionLink', to='flow_builder_app.nodeversion'),
        ),
        migrations.CreateModel(
            name='NodeParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('node_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='flow_builder_app.nodeversion')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_parameters', to='flow_builder_app.parameter')),
            ],
            options={
                'verbose_name': 'Version Parameter',
            },
        ),
        migrations.CreateModel(
            name='SubNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_deployed', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('version_comment', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnodes', to='flow_builder_app.nodefamily')),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='flow_builder_app.subnode')),
            ],
            options={
                'ordering': ['node_family', 'name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow_builder_app.parameter')),
                ('subnode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='flow_builder_app.subnode')),
            ],
        ),
        migrations.CreateModel(
            name='SubNodeParameterValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow_builder_app.parameter')),
                ('subnode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametervalues', to='flow_builder_app.subnode')),
            ],
        ),
        migrations.AddIndex(
            model_name='nodefamily',
            index=models.Index(fields=['name'], name='flow_builde_name_cabf48_idx'),
        ),
        migrations.AddIndex(
            model_name='nodefamily',
            index=models.Index(fields=['is_deployed'], name='flow_builde_is_depl_3d1c40_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeexecution',
            index=models.Index(fields=['version', 'status'], name='flow_builde_version_e4b59b_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeexecution',
            index=models.Index(fields=['status'], name='flow_builde_status_147cd6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeversionlink',
            unique_together={('parent_version', 'child_version')},
        ),
        migrations.AddIndex(
            model_name='nodeversion',
            index=models.Index(fields=['family', 'state'], name='flow_builde_family__1b1498_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeversion',
            index=models.Index(fields=['state'], name='flow_builde_state_076cb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeversion',
            unique_together={('family', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='nodeparameter',
            unique_together={('node_version', 'parameter')},
        ),
        migrations.AlterUniqueTogether(
            name='subnode',
            unique_together={('node_family', 'name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='parametervalue',
            unique_together={('parameter', 'subnode')},
        ),
        migrations.AlterUniqueTogether(
            name='subnodeparametervalue',
            unique_together={('subnode', 'parameter')},
        ),
    ]
